[package]
name = "relay"
version = "0.0.0"
publish = false
edition = "2018"

[dependencies]
tokio = { version = "0.2", features = ["full"] }
tokio-util = { version = "0.2", features = ["full"] }
bytes = "0.5"
futures = "0.3"

[[bin]]
name = "relay"
path = "relay.rs"
